test:
  tags:
    - shell
  only:
    - for_testing
  script:
    - virtualenv .env
    - source .env/bin/activate
    - pip3 install coverage
    - make test
    - make clean
    - deactivate
    - rm -rf .env
