stages:
  - test

test:
  stage: test
  image: ubuntu:latest
  tags:
    - linuxrunner
  script:
    - apt update
    - apt install python3 -y
    - apt install python-virtualenv -y
    - python --version
    - virtualenv -p python3 .env
    - source .env/bin/activate
    - python --version
    - pip install coverage
    - make test
    - make clean
    - deactivate
    - rm -rf .env
