stages:
  - test

test:
  stage: test
  image: ubuntu:latest
  tags:
    - linuxrunner
  script:
    - apt-get install python-virtualenv
    - virtualenv .env
    - source .env/bin/activate
    - pip3 install coverage
    - make test
    - make clean
    - deactivate
    - rm -rf .env
